'use client';
import React from 'react';
import { BookOpen } from 'lucide-react';
import iconMapping from './Icon.Script/icon_mapping.json';

interface CourseIconProps {
    courseName: string;
    size?: number;
    className?: string;
}

export function CourseIcon({ courseName, size = 20, className = "" }: CourseIconProps) {
    const getIconPath = (name: string) => {
        // Clean name to match JSON keys (lowercase, remove spaces, underscores, hyphens)
        const key = name.toLowerCase().replace(/[\s\-_]/g, '');

        // Direct lookup from the JSON mapping generated by the Python script
        return (iconMapping as Record<string, string>)[key] || null;
    };

    const iconPath = getIconPath(courseName);

    if (iconPath) {
        return (
            <img
                src={iconPath}
                alt={courseName}
                style={{ width: size, height: size, objectFit: 'contain' }}
                className={className}
                onError={(e) => {
                    // Fallback to lucide icon if image fails to load
                    (e.target as any).style.display = 'none';
                    (e.target as any).nextSibling.style.display = 'block';
                }}
            />
        );
    }

    // Default Lucide Icon if no mapping found
    return <BookOpen size={size} className={className} />;
}
